# Generated by Django 5.0.1 on 2025-11-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrutalMathSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('closing_text', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brutal Math Section',
                'verbose_name_plural': 'Brutal Math Section',
            },
        ),
        migrations.CreateModel(
            name='BrutalMathStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brutal Math Stat',
                'verbose_name_plural': 'Brutal Math Stats',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comparison Table',
                'verbose_name_plural': 'Comparison Table',
            },
        ),
        migrations.CreateModel(
            name='ComparisonTableFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typical', models.BooleanField(default=False)),
                ('centaura', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.comparisontable')),
            ],
            options={
                'verbose_name': 'Comparison Table Feature',
                'verbose_name_plural': 'Comparison Table Features',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalWordSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final Word Section',
                'verbose_name_plural': 'Final Word Section',
            },
        ),
        migrations.CreateModel(
            name='PeopleBehindStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True, null=True)),
                ('jane_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jane_title', models.CharField(blank=True, max_length=200, null=True)),
                ('jane_image_url', models.URLField(blank=True, null=True)),
                ('jane_bio', models.JSONField(blank=True, default=list)),
                ('aimun_name', models.CharField(blank=True, max_length=200, null=True)),
                ('aimun_title', models.CharField(blank=True, max_length=200, null=True)),
                ('aimun_image_url', models.URLField(blank=True, null=True)),
                ('aimun_bio', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'People Behind Strategy',
                'verbose_name_plural': 'People Behind Strategy',
            },
        ),
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Section',
                'verbose_name_plural': 'Process Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.processsection')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyCentauraFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Centaura Feature',
                'verbose_name_plural': 'Why Centaura Features',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyCentauraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Centaura Section',
                'verbose_name_plural': 'Why Centaura Section',
            },
        ),
        migrations.CreateModel(
            name='WhyWeBuiltSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(blank=True, max_length=200, null=True)),
                ('left_content', models.JSONField(blank=True, default=list)),
                ('right_title', models.CharField(blank=True, max_length=200, null=True)),
                ('right_content', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why We Built Section',
                'verbose_name_plural': 'Why We Built Section',
            },
        ),
        migrations.DeleteModel(
            name='FAQSection',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='ServicesSection',
        ),
        migrations.AddField(
            model_name='hero',
            name='founders_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hero',
            name='founders_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='founders_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
