# Generated by Django 5.0.1 on 2025-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_brutalmathsection_brutalmathstat_comparisontable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='secure_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
