# Generated by Django 5.0.1 on 2025-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_mediaasset_secure_url_alter_mediaasset_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwordsection',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
